#https://home-assistant.io/components/sensor/

####################################################
#                                                  #
#                      PLEX                        #
#                                                  #
####################################################

#https://github.com/custom-components/sensor.plex_recently_added
- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port
  section_types:
    - movie
