substitutions:
  devicename: balcony_light
  upper_devicename: Balcony Light
  mqtt_broker: !secret mqtt_host

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${upper_devicename} Fallback Hotspot
    password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.1.229
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
      
captive_portal:
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass

sensor:
  - platform: wifi_signal
    name: "Balcony Light WiFi Signal"
    update_interval: 15s
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      then:
        - light.toggle: light_1

  - platform: status
    name: Balcony Light Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "Balcony Light"
    id: light_1
    output: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes    
