substitutions:
  devicename: kitchenlight
  upper_devicename: Kitchen Light
  mqtt_broker: !secret mqtt_host

esphome:
  name: $devicename  
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${upper_devicename} Fallback Hotspot
    password: !secret wifi_password
      
captive_portal:
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      then:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: button2
    on_press:
      then:
        - light.toggle: light_2

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

  - platform: gpio
    pin: GPIO5
    id: relay_2

light:
  - platform: binary
    name: "Sub Balcony Light"
    id: light_1
    output: relay_1

  - platform: binary
    name: "Kitchen Light"
    id: light_2
    output: relay_2

status_led:
  pin:
    number: GPIO13
    inverted: yes