substitutions:
  devicename: livingroom_sensor
  upper_devicename: LR Sensor
  mqtt_broker: !secret mqtt_host

esphome:
  name: $devicename
  platform: ESP32
  board: pico32
  platformio_options:
    upload_speed: 115200

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${upper_devicename} Fallback Hotspot
    password: !secret wifi_password
      
captive_portal:
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass

i2c:
  - id: grove_bus
    sda: GPIO26
    scl: GPIO32
    scan: True

esp32_ble_tracker:

sensor:
  - platform: uptime
    name: ${upper_devicename} System Uptime
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
    
  - platform: sgp30
    eco2:
      name: "Livingroom eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "Livingroom TVOC"
      accuracy_decimals: 1
    address: 0x58
    update_interval: 5s
  # - platform: bmp280
  #   temperature:
  #     name: "Livingroom Temperature"
  #     oversampling: 16x
  #   pressure:
  #     name: "Livingroom Pressure"
  #   address: 0x58
  #   update_interval: 60s    

remote_receiver:
  id: rcvr
  pin:
    number: GPIO33
    inverted: True
    mode: INPUT_PULLUP
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%
  
# remote_transmitter:
#   pin: GPIO22
#   carrier_duty_percent: 50%
  
# climate:
#   - platform: climate_ir_lg
#     name: "Living Room AC"
#     receiver_id: rcvr

  
switch:
  - platform: restart
    name: ${upper_devicename} Restart
