###############################################################################
#   @author         :   Wannarut Bunsang
#   @date           :   18/12/2019
#   @package        :   Washing Machine
#   @description    :   
#   @url            :   https://philhawthorne.com/making-dumb-dishwashers-and-washing-machines-smart-alerts-when-the-dishes-and-clothes-are-cleaned/
###############################################################################
homeassistant:
  customize:
    sensors.washing_machine_current_power_w:
      friendly_name: Power 
      icon: mdi:flash
    sensors.washing_machine_door_status:
      icon: mdi:glassdoor
      friendly_name: 'Washing Machine Door'
    sensors.washing_machine_status:
      icon: mdi:lamp
      friendly_name: 'Washing Machine Status'
    switch.washing_machine:
      friendly_name: Switch
      icon: mdi:power-plug


###############################################################################
#                                 SENSOR                                      #
###############################################################################
sensor:
  - platform: template
    sensors:
      washing_machine_current_power_w:
        value_template: '{{ states.switch.washing_machine.attributes.current_power_w }}'
        unit_of_measurement: 'Watt'
      washing_machine_door_status:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d00027b429d %}
          {% if states.binary_sensor.door_window_sensor_158d00027b429d.state == "on" %}
            Open
          {% else %}
            Closed
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'

###############################################################################
#                              INPUT SELECT                                   #
###############################################################################

input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle

###############################################################################
#                               Automations                                   #
###############################################################################
automation:        
# When power is detected, and the washing machine is not in 
# the Running state, change the status of the washing machine
# to Running. 
# The status check will ensure we don't try to put the state 
# to Running each time the power level changes, and we're already
# in the Running state.
- alias: Set washing machine active when power detected
  id: washingmachine01
  initial_state: true 
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_current_power_w
      above: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Idle
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Clean
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running
    - service: timer.start
      entity_id: timer.washing_machine_time_left

# When the power drops, move the state of the washing machine to 
# Finishing.
- alias: Set washing machine finished when power drops
  id: washingmachine02
  initial_state: true 
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_current_power_w
      below: 4
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Finishing

- alias: Send alert when washing machine is finished
  id: washingmachine03
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.washing_machine_status
      to: Clean
      for:
        minutes: 1
    - platform: state
      entity_id: person.peamai
      to: 'home'
      for:
        minutes: 2
    - platform: state
      entity_id: person.wanball
      to: 'home'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:00:00'
        after: '08:00:00'    
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Clean
      - condition: template
        value_template: >
          {% if states.automation.send_alert_when_washing_machine_is_finished.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_when_washing_machine_is_finished.attributes.last_triggered) | int > 1800 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}  
  action:
    - service: script.turn_on
      entity_id: script.say_washing_machine_finishing

# Wait 2 minutes for us to be in the Finishing state before we
# decide the washing machine has finished. This way, if the 
# washing machine is in between cycles and the power drops, we 
# won't mark the washing machine cycle as finished too early.
- alias: Set washing machine clean after timeout
  id: washingmachine04
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_status
      to: Finishing
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Clean

- alias: Set washing machine to Idle
  id: washingmachine05
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.washing_machine
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Idle

# When we open the washing machine door, reset the status back to
# idle, so we don't spam people that the washing machine has 
# finished, and someone has already emptied it
- alias: Set washing machine dirty when door opens
  id: washingmachine06
  initial_state: true
  trigger:
      # I've setup a template sensor to change make the binary_sensor report open and closed
      # instead of 1 and 0
    - platform: state
      entity_id: sensor.washing_machine_door_status
      to: 'Open'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Idle

- alias: Turn off washing machine when nobody's home
  id: washingmachine07
  initial_state: true 
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Idle
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.washing_machine

###############################################################################
#                                 SCRIPT                                      #
###############################################################################
script:
  say_washing_machine_finishing:
    sequence:
    - service: media_player.turn_on
      data:
        entity_id: media_player.living_room_speaker
    - delay:
        milliseconds: 150
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_speaker
        volume_level: "1"
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data_template:
        message: '{{ ["เครื่องซักผ้าทำงานเสร็จสิ้นแล้วค่ะ", "เครื่องซักผ้าเสร็จสิ้นการทำงานแล้วค่ะ", "เครื่องซักผ้าจบการทำงาน มีผ้ารอตากอยู่ค่ะ" ] | random }}'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_speaker
        volume_level: "0.5"

###############################################################################
#                                 TIMER                                       #
###############################################################################
timer:
  washing_machine_time_left:
    duration: '01:00:00'

####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################